import turtle
# t = turtle.Pen()
# my_color = ("red","green","yellow","black")
# for x in range(10):
#     t.width(5)
#     t.penup()
#     t.goto(0,-x*10)
#     t.pendown()
#     t.color(my_color[x%len(my_color)])
#     t.circle(10*(x+1))
# turtle.done()
t = turtle.Pen()
# t.penup()
# t.goto(0,180)
# t.pendown()
# t.goto(180,180)
# t.penup()
# t.goto(0,172)
# t.pendown()
# t.goto(180,172)
for i in range(0,19):
    t.penup()
    t.goto(0,i*10)
    t.pendown()
    t.goto(180,i*10)
for j in range(0,19):
    t.penup()
    t.goto(j*10,0)
    t.pendown()
    t.goto(j*10,180)
turtle.done()